controllers:
    resource: ../../src/Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

api_controllers:
    resource: ../../src/Api/
    type: attribute
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: attribute
