#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /{_locale}
  controller: App\Controller\DefaultController::home
  requirements:
    _locale: '%app_locales%'
  defaults:
    template: default/homepage.html.twig
    _locale: '%locale%'
