# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: es
    app_locales: es|en
    adjunto_directory: '%kernel.project_dir%/public/media'
    default_results_per_page: { '10': 10,'25': 25, '100': 100, '1000': 1000 }
    app.target_directory_uploader: '%kernel.project_dir%/public/upload'
    app.token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJydWMiOiIyMDUyOTc1MjQ3NSIsIm5hbWUiOiJQaWRpYSBTUkwifQ.hHV7UizWn4E4R3KxUjC1B0BPH3yfB-NNYsoerUc0XWQ
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind: # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
            $emailSender: 'cio@pidia.pe'
            $targetDirectoryUploader: '%app.target_directory_uploader%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%adjunto_directory%'
    App\EventListener\AdjuntoUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
    pagerfanta.view.low_proximity_and_spanish_messages:
        class: Pagerfanta\View\OptionableView
        arguments:
            - '@pagerfanta.view.twitter_bootstrap4'
            - { proximity: 2, prev_message: Anterior, next_message: Siguiente }
        public: false
        tags:
            - { name: pagerfanta.view, alias: low_proximity_and_spanish_messages }
